#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.4.6f1_cde1bbcc9f0d"
#define UNITY_VERSION_FULL_NICE "2018.4.6f1 (cde1bbcc9f0d)"
#define UNITY_VERSION_BLD 13492667
#define UNITY_VERSION_DATE 1564674860
#define UNITY_VERSION_WIN "2018.4.6.13492667"
#define UNITY_VERSION_BRANCH "2018.4/staging"
